parameters:

services:
    onelogin_auth:
        abstract: true
        class: OneLogin\Saml2\Auth
        arguments: [ "%hslavich_onelogin_saml.settings%"]
        public: true

    Hslavich\OneloginSamlBundle\Security\Utils\OneLoginAuthRegistry:
        arguments:
            - "@security.http_utils"

    hslavich_onelogin_saml.user_provider:
        class: Hslavich\OneloginSamlBundle\Security\User\SamlUserProvider

    hslavich_onelogin_saml.saml_provider:
        class: Hslavich\OneloginSamlBundle\Security\Authentication\Provider\SamlProvider
        arguments: [""]

    hslavich_onelogin_saml.saml_token_factory:
        class: Hslavich\OneloginSamlBundle\Security\Authentication\Token\SamlTokenFactory

    hslavich_onelogin_saml.saml_authentication_success_handler:
        class: Hslavich\OneloginSamlBundle\Security\Authentication\SamlAuthenticationSuccessHandler
        parent: security.authentication.success_handler

    hslavich_onelogin_saml.saml_listener:
        class: Hslavich\OneloginSamlBundle\Security\Firewall\SamlListener
        parent: security.authentication.listener.abstract
        abstract: true
        calls:
            - [ setAuthRegistry, ["@Hslavich\\OneloginSamlBundle\\Security\\Utils\\OneLoginAuthRegistry"] ]

    hslavich_onelogin_saml.saml_logout:
        class: Hslavich\OneloginSamlBundle\Security\Logout\SamlLogoutHandler
        arguments:
            - "@Hslavich\\OneloginSamlBundle\\Security\\Utils\\OneLoginAuthRegistry"

    Hslavich\OneloginSamlBundle\Controller\SamlController:
        arguments:
            - "@Hslavich\\OneloginSamlBundle\\Security\\Utils\\OneLoginAuthRegistry"
